# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b86467e609d77f4530dc6649785b6cea"
name = "ShipMath"
application_url = "https://example.com"
embedded = true
handle = "ship-math"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
